export const GET_PRODUCTS_REQUEST = "[products] GET_PRODUCTS_REQUEST"
export const GET_PRODUCTS_SUCCESS = "[products] GET_PRODUCTS_SUCCESS"
export const GET_PRODUCTS_ERROR = "[products] GET_PRODUCTS_ERROR"

export const CREATE_PRODUCT_REQUEST = "[products] CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "[products] CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_ERROR = "[products] CREATE_PRODUCT_ERROR"

export const UPDATE_PRODUCT_REQUEST = "[products] UPDATE_PRODUCT_REQUEST"
export const UPDATE_PRODUCT_SUCCESS = "[products] UPDATE_PRODUCT_SUCCESS"
export const UPDATE_PRODUCT_ERROR = "[products] UPDATE_PRODUCT_ERROR"

export const DELETE_PRODUCT_REQUEST = "[products] DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "[products] DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_ERROR = "[products] DELETE_PRODUCT_ERROR"