export const AUTHENTICATE_REQUEST = '[auth] AUTHENTICATE_REQUEST'
export const AUTHENTICATE_SUCCESS = '[auth] AUTHENTICATE_SUCCESS'
export const AUTHENTICATE_ERROR = '[auth] AUTHENTICATE_ERROR'

export const SIGN_OUT = '[auth] SIGN_OUT'

export const REGISTER_REQUEST = '[auth] REGISTER_REQUEST'
export const REGISTER_SUCCESS = '[auth] REGISTER_SUCCESS'

export const UPDATE_USER_REQUEST = '[auth] UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS = '[auth] UPDATE_USER_SUCCESS'
export const UPDATE_USER_ERROR = '[auth] UPDATE_USER_ERROR'