export { default as RegisterPage } from './RegisterPage'
export { default as RegisterFormWrapper } from './RegisterFormWrapper'
export { default as RegisterForm } from './RegisterForm'
export { default as RegisterAccountInformationStep } from './RegisterAccountInformationStep'
export { default as RegisterCompanyDetailsStep } from './RegisterCompanyDetailsStep'
export { default as RegisterPersonalDataStep } from './RegisterPersonalDataStep'
export { default as RegisterAccountCreatedStep } from './RegisterAccountCreatedStep'