export const LOAD_MATERIALS_REQUEST = '[material] LOAD_MATERIALS_REQUEST'
export const LOAD_MATERIALS_SUCCESS = '[material] LOAD_MATERIALS_SUCCESS'
export const LOAD_MATERIALS_ERROR = '[material] LOAD_MATERIALS_ERROR'

export const SEARCH_SUGGESTIONS_REQUEST = '[material] SEARCH_SUGGESTIONS_REQUEST'
export const SEARCH_SUGGESTIONS_SUCCESS = '[material] SEARCH_SUGGESTIONS_SUCCESS'
export const SEARCH_SUGGESTIONS_ERROR = '[material] SEARCH_SUGGESTIONS_ERROR'